CC=javac

# The target
all: Server.class Client.class

# To generate the class files
Server.class: Server.java
	$(CC) Server.java


Client.class: Client.java
	$(CC) Client.java

Record.class: Record.java
	$(CC) Record.java
# clean out the dross
clean:
	-rm *.class
